version: "3.8"
services:
  db_federal:
    image: "postgres"
    container_name: "database"
    ports:
      - "5432:5432"
    volumes:
      - /var/www/html/database:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spravki
  main_service:
    build: ./
    container_name: "spravki"
    restart: always
    ports:
      - "80:80"